format = """
[  ](fg:bold dir_color bg:bg3)\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""


palette = "compline"

[palettes.compline]
bg1 = "#2D2A2E"
bg2 = "#221F22"
bg3 = "#19181A"

fg_main = "#FCFCFA"
fg_dim  = "#b4c0c8"
fg_dir  = "#ccc4b4"

# styles here https://monokai.pro/contribute
accent  = "#d3869b"
dir_color = "#A9DC76"
branch = "#C1C0C0"
dirt_status = "#FF6188"
chng_status = "#78DCE8"
# shared colors (mental model)
# bg1 = #282c34
# bg2 = #3d424a
# fg_main = #e0dcd4
# fg_dim = #b4c0c8
# fg_dir = #ccc4b4

[directory]
style = "fg:bold dir_color bg:bg2"
# style = "fg:bold bg2 bg:dir_color"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "fg:italic branch bg:bg1"
format = "[ $symbol $branch ]($style)"
# ignore_branches=['main']

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted )](fg:dirt_status bg:bg1)($ahead_behind$stashed )]($style)"
style = "fg:chng_status bg:bg1"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
style = "fg:#b4c0c8 bg:bg1"
format = '[\($state( $progress_current/$progress_total)\)]($style)'

[cmd_duration]
style = "bg:#2e2e2e"
format = "[[  $duration ](fg:#1a1d21 bg:#e0dcd4)]($style)"

[python]
style = "italic fg:#b4c0c8 bg:#282c34"
format = "[ $virtualenv(fg:#282c34 bg:none )]($style)"

# [character]
# format = '$symbol '
# success_symbol= " [❯](bold green)"
# error_symbol= "[ ❯](bold red)"
